# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "simpleblog"
license = "Apache License 2.0"
licenselink = "https://github.com/ymotongpoo/simpleblog/blob/master/LICENSE.md"
description = "Simple blog template for Hugo"
homepage = "https://github.com/ymotongpoo/simpleblog/"
tags = ["blog", "simple"]
features = ["", ""]
min_version = 0.14

[author]
  name = "Yoshi Yamaguchi"
  homepage = "https://github.com/ymotongpoo/"
